### ISSUE TITLE
tr vs td usage

### ISSUE THREAD

**Issue by marcelloh** [HakamFostok/Paging-Knockout#2]
I found this awsome piece of software, for which I thank you.
But I also found this part:
```
 <tr data-bind="text:$data.name"></tr>
```
in my opinion, this should be, because people could need more fields to show, and it is valid html.
```
 <tr>
 <td data-bind="text:$data.name"></td>
 </tr>
```

Just my 2 cents ;-)

**Comment by HakamFostok** [comment]
Can you please specify the file name in which you found this, I could not found this actually.

**Comment by marcelloh** [comment]
Example.html line 23

**Comment by HakamFostok** [comment]
Thank you very much for the note, I really appreciate it. I had fixed this according to your suggestion, you can check out the new version. Thanks again, and I will close this Issue because it has been fixed.
